"""Third Migration

Revision ID: 561819a8985e
Revises: 99b42e9784cb
Create Date: 2022-05-16 15:25:18.851358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561819a8985e'
down_revision = '99b42e9784cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'subtitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('subtitle', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
