"""Second Migration

Revision ID: 99b42e9784cb
Revises: 86c5c8ec4812
Create Date: 2022-05-16 15:13:53.813895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b42e9784cb'
down_revision = '86c5c8ec4812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('title', sa.String(length=20), nullable=True))
    op.add_column('blogs', sa.Column('subtitle', sa.String(length=20), nullable=True))
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'subtitle')
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
